version: "4.1"



services:
  web:
    build: .
    command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000 # new
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=p_o3vp1rg5)t^lxm9-43%0)s-=1qpeq%o7gfq+e4#*!t+_ev82
      - DEBUG=0
      - RAZORPAY_KEY_ID = 'rzp_live_y4lUUCW4dMTSwc'
      - RAZORPAY_KEY_SECRET = 'qtKSYK2ONRu9iNstut4hhqCj'
      
      
    volumes:
      - .:/books
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: