databases:
  - name: books
    databaseName: postgres
    user: postgres

services:
  - type: web
    name: books
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn books.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: p_o3vp1rg5)t^lxm9-43%0)s-=1qpeq%o7gfq+e4#*!t+_ev82
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4